### ISSUE TITLE
Missing primitive: `ml_z_extract_small`

### ISSUE THREAD

**Issue by bclement-ocp** [janestreet/zarith_stubs_js#10]
`ml_z_extract_small` was added as a fast path for `ml_z_extract` in ZArith 1.13 (see https://github.com/ocaml/Zarith/pull/90 )

It can be aliased to `ml_z_extract`:

```ocaml
// Provides: ml_z_extract_small
// Requires: ml_z_extract
function ml_z_extract_small(z1, pos, len) {
  return ml_z_extract(z1, pos, len);
}
```

**Comment by hhugo** [comment]
@TyOverby, @pmwhite would you be able to look at this ?

**Comment by Enoumy** [comment]
Thanks for reporting this and thanks for the suggested fix! The patch has been imported internally and should appear on the public release on our next push of our packages.

Thanks!

**Comment by hhugo** [comment]
@Enoumy, do you think you could do a minor release of zarith_stubs_js with this change ?

**Comment by dkalinichenko-js** [comment]
@hhugo I'll do it shortly
