### ISSUE TITLE
zarith uses `caml_custom_ops` that is not in js_of_ocaml 3.4.0

### ISSUE THREAD

**Issue by abate** [janestreet/zarith_stubs_js#3]
The function `caml_custom_ops` is used here, and in the master branch of js_of_ocaml. It is not in an official release of jsoo.

Maybe, you can add a specific version of js_of_ocaml in the opam dependencies to avoid these problems in the future.

Thank you !

**Comment by hhugo** [comment]
It should work with the master branch of js_of_ocaml. I'll try to release js_of_ocaml soon

**Comment by abate** [comment]
do you have an ETA about this ? there are few other libraries I use (cohttp) that don't work with jsoo master (as they are waiting for the next release), so to make everything work is getting a bit complicated on my side.

**Comment by hhugo** [comment]
Hopefully next weekend.

**Comment by hhugo** [comment]
js_of_ocaml has been released. Things should work now (with js_of_ocaml-compiler.3.5.0)

**Comment by abate** [comment]
fanstatic . thank you so much for your help !
