### ISSUE TITLE
Issue with Q.compare raising Stdlib error

### ISSUE THREAD

**Issue by ACoquereau** [janestreet/zarith_stubs_js#4]
Hi,
Thanks for this library, i'm trying to use it in the JS version of the SMT solver Alt-Ergo and i've found an error. I manage to make a minimal example of my problem:  
```
let () =
  let y = Q.of_string "21749119135811171023142898368512/7209762788798054855747370097333" in
  print_int (Q.compare y y)
```
This lines issued the following error :
```
dune build; node _build/default/Main.bc.js
                     
<my_path>/_build/default/Main.bc.js:83
    function caml_raise_with_arg(tag,arg){throw [0,tag,arg]}
                                          ^
[
  0,
  [ 248, MlBytes { t: 9, c: 'Invalid_argument', l: 16 }, -3 ],
  MlBytes { t: 9, c: 'compare: abstract value', l: 23 }
]
```
The `compare: abstract value` error message seems to be issued by the compare function of the stdlib. But, in Zarith, Q use the comparison of Z which use an external `ml_z_compare`. Your runtime seems to provide this primitive using the bigInt comparison. I don't understand why i get an error message from the stdlib since your library provides every things that i need. Do i correctly use your library ?

[test_zarith_stubs.zip](https://github.com/janestreet/zarith_stubs_js/files/4544498/test_zarith_stubs.zip)

**Comment by hhugo** [comment]
This is fixed on master (in https://github.com/janestreet/zarith_stubs_js/commit/850bdc48de569361d27bd014d4b19802854a61ed).
Can you pin the package the latest version until we make an official release ?

@xclerc when do we expect the next official release of our packages ?

**Comment by ACoquereau** [comment]
Pinning to the latest version works, thanks.
Since the JS version of Alt-Ergo is under development i don't see any issue to let the package pinned until the next release of your lib.
Thanks for your work

**Comment by xclerc** [comment]
The next stable release is expected to occur in May/June,
but we can certainly do a v0.13.1 release before.

**Comment by ACoquereau** [comment]
May/June is good for us since we will not publish a new JS version of Alt-Ergo until June/July, thanks
