### ISSUE TITLE
Provide documentation for how to use this

### ISSUE THREAD

**Issue by davidmurdoch** [janestreet/zarith_stubs_js#5]
We've been stuck on how to actually use this in a project that uses Zarith. An example in the README would be awesome!

**Comment by hhugo** [comment]
We'll improve the README.

If you use dune, just add `zarith_stubs_js` as a library dependency to you project.

If you don't use dune, you need to find a way to pass  both `biginteger.js` and `runtime.js` files to the js_of_ocaml compiler command line.

**Comment by xclerc** [comment]
Fixed by https://github.com/janestreet/zarith_stubs_js/commit/6502401bbae89f2affae2d68c4359dc1242d13c1.
