### ISSUE TITLE
Release on OPAM?

### ISSUE THREAD

**Issue by jnfoster** [janestreet/zarith_stubs_js#7]
Not to be rude, but is there a timeline for an updated OPAM release? The pre-v0.15 version has been sitting for several months.

The bugfix discussed here,
https://github.com/janestreet/zarith_stubs_js/commit/7c5a500f2b63957a1267e493635b92c32dd647ea
is important for our project. It's slightly clunky (but not impossible of course) to install it from source rather than OPAM.

Thanks!

**Comment by hackedy** [comment]
Any updates on this? The patch is now a year old and still not available on OPAM.
