### ISSUE TITLE
Using Native JS BigInt

### ISSUE THREAD

**Issue by maxtori** [janestreet/zarith_stubs_js#9]
Just before the first release of zarith_stubs_js, I had written a stubs using the new [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) built-in (only for my needs so not exhaustive). But of course some Safari users complained...
Since Safari has finally implemented BigInt (since october 2020), would you be inclined to review a PR switching to this native implementation ?

**Comment by hhugo** [comment]
I believe the current implementation will use native BigInt if available.

**Comment by maxtori** [comment]
my bad...

**Comment by TyOverby** [comment]
To be a bit more precise, the library that we include is primarily a polyfill for the native big-int support that browsers have.  If they exist, it uses them, otherwise, it falls back to a custom implementation.  I hope that this is sufficient for your needs!
